title = "Data Visualization Research Lab"
baseURL = "https://ccom.unh.edu/vislab/"
languageCode = "en-us"
paginate = 6

canonifyurls=true

[params]
  builtBy = "ahs"
  defaultImage = "VisLab_Logo_Black.png"

  email = "astevens@ccom.unh.edu"

  custom_css = ["css/custom.css"]

  [params.copyright]
     name = "CCOM"
     link = "https://ccom.unh.edu"